# Generated by Django 3.0.3 on 2020-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_problem_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_select',
            name='problem_date_select',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
