# Generated by Django 3.0.3 on 2020-03-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_auto_20200318_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_select',
            name='problem_date_select',
            field=models.DateField(),
        ),
    ]
